# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzsvgerUetZeEnfQG90U07_e-jecmAad
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# Step 1: Create a High-Resolution Synthetic Image
# ------------------------------------------------------------
image = np.ones((400, 400, 3), dtype=np.uint8) * 255

# Draw objects
cv2.rectangle(image, (40,40), (160,180), (255,0,0), -1)
cv2.circle(image, (300,100), 50, (0,255,0), -1)
cv2.line(image, (40,300), (360,300), (0,0,255), 5)

cv2.putText(image, "CAR", (70,120),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8, (255,255,255), 2)

cv2.putText(image, "TREE", (250,110),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6, (0,0,0), 2)

# ------------------------------------------------------------
# Step 2: Simulate Low Sampling (Low Resolution)
# ------------------------------------------------------------
low_res = cv2.resize(image, (80,80),
                     interpolation=cv2.INTER_AREA)

# Upscale back to original size
low_res_up = cv2.resize(low_res, (400,400),
                        interpolation=cv2.INTER_NEAREST)

# ------------------------------------------------------------
# Step 3: Improve Visibility
# ------------------------------------------------------------
improved = cv2.GaussianBlur(low_res_up, (3,3), 0)

# ------------------------------------------------------------
# Step 4: Display Images
# ------------------------------------------------------------
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.title("High Resolution")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(cv2.cvtColor(low_res_up, cv2.COLOR_BGR2RGB))
plt.title("Low Resolution (Low Sampling)")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(cv2.cvtColor(improved, cv2.COLOR_BGR2RGB))
plt.title("After Image Processing")
plt.axis("off")

plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# Step 5: Save Images
# ------------------------------------------------------------
cv2.imwrite("high_resolution.jpg", image)
cv2.imwrite("low_resolution.jpg", low_res_up)
cv2.imwrite("processed_image.jpg", improved)

print("Experiment Completed Successfully!")
print("Images Saved:")
print("1. high_resolution.jpg")
print("2. low_resolution.jpg")
print("3. processed_image.jpg")