# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzsvgerUetZeEnfQG90U07_e-jecmAad
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Create a synthetic grayscale image
image = np.tile(np.arange(256, dtype=np.uint8), (256,1))

# Quantization function
def quantize(img, levels):
    step = 256 // levels
    return (img // step) * step

q256 = image
q64 = quantize(image, 64)
q16 = quantize(image, 16)
q8 = quantize(image, 8)
q4 = quantize(image, 4)
q2 = quantize(image, 2)

plt.figure(figsize=(12,7))

titles = ["256 Levels", "64 Levels", "16 Levels",
          "8 Levels", "4 Levels", "2 Levels"]

images = [q256, q64, q16, q8, q4, q2]

for i in range(6):
    plt.subplot(2,3,i+1)
    plt.imshow(images[i], cmap='gray')
    plt.title(titles[i])
    plt.axis("off")

plt.tight_layout()
plt.show()