# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzsvgerUetZeEnfQG90U07_e-jecmAad
"""

# ============================================================
# Experiment 9:
# Computer Vision Levels in Facial Recognition
#
# Aim:
# Demonstrate the stages of facial recognition:
# 1. Image Acquisition
# 2. Image Preprocessing
# 3. Face Detection
# 4. Decision Making
#
# No external image is required.
# ============================================================

import cv2
import numpy as np
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# Step 1: Create a Synthetic Face Image
# ------------------------------------------------------------
image = np.ones((300,300,3), dtype=np.uint8) * 255

# Face
cv2.circle(image, (150,150), 90, (255,220,180), -1)

# Eyes
cv2.circle(image, (120,125), 10, (0,0,0), -1)
cv2.circle(image, (180,125), 10, (0,0,0), -1)

# Nose
cv2.line(image, (150,140), (150,175), (0,0,0), 2)

# Smile
cv2.ellipse(image, (150,190), (35,18), 0, 0, 180, (0,0,255), 2)

# ------------------------------------------------------------
# Step 2: Image Acquisition
# ------------------------------------------------------------
original = image.copy()

# ------------------------------------------------------------
# Step 3: Image Preprocessing
# ------------------------------------------------------------
gray = cv2.cvtColor(original, cv2.COLOR_BGR2GRAY)

blur = cv2.GaussianBlur(gray, (5,5), 0)

# ------------------------------------------------------------
# Step 4: Face Detection (Simulation)
# ------------------------------------------------------------
detected = original.copy()

# Draw bounding box around face
cv2.rectangle(detected, (60,60), (240,240), (0,255,0), 3)

cv2.putText(
    detected,
    "Face Detected",
    (70,50),
    cv2.FONT_HERSHEY_SIMPLEX,
    0.7,
    (0,0,255),
    2
)

# ------------------------------------------------------------
# Step 5: Decision Making
# ------------------------------------------------------------
decision = detected.copy()

cv2.putText(
    decision,
    "Decision: Person Recognized",
    (20,280),
    cv2.FONT_HERSHEY_SIMPLEX,
    0.7,
    (255,0,0),
    2
)

# ------------------------------------------------------------
# Display Results
# ------------------------------------------------------------
plt.figure(figsize=(12,8))

plt.subplot(2,2,1)
plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
plt.title("1. Image Acquisition")
plt.axis("off")

plt.subplot(2,2,2)
plt.imshow(blur, cmap="gray")
plt.title("2. Image Preprocessing")
plt.axis("off")

plt.subplot(2,2,3)
plt.imshow(cv2.cvtColor(detected, cv2.COLOR_BGR2RGB))
plt.title("3. Face Detection")
plt.axis("off")

plt.subplot(2,2,4)
plt.imshow(cv2.cvtColor(decision, cv2.COLOR_BGR2RGB))
plt.title("4. Decision Making")
plt.axis("off")

plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# Save Images
# ------------------------------------------------------------
cv2.imwrite("face_original.jpg", original)
cv2.imwrite("face_preprocessed.jpg", blur)
cv2.imwrite("face_detected.jpg", detected)
cv2.imwrite("face_decision.jpg", decision)

print("Facial Recognition Simulation Completed Successfully!")
print("Images Saved:")
print("1. face_original.jpg")
print("2. face_preprocessed.jpg")
print("3. face_detected.jpg")
print("4. face_decision.jpg")