# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzsvgerUetZeEnfQG90U07_e-jecmAad
"""

# ============================================================
# Experiment 8:
# Image Acquisition Noise and Noise Reduction
#
# Aim:
# Simulate sensor noise during image acquisition and
# minimize it using image filtering techniques.
#
# No external image is required.
# ============================================================

import cv2
import numpy as np
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# Step 1: Create a Synthetic Grayscale Image
# ------------------------------------------------------------
image = np.zeros((256, 256), dtype=np.uint8)

# Draw simple objects
cv2.rectangle(image, (40,40), (120,120), 180, -1)
cv2.circle(image, (190,70), 35, 255, -1)
cv2.rectangle(image, (70,160), (220,230), 100, -1)

# ------------------------------------------------------------
# Step 2: Simulate Sensor Noise (Gaussian Noise)
# ------------------------------------------------------------
noise = np.random.normal(0, 25, image.shape).astype(np.int16)

noisy = image.astype(np.int16) + noise
noisy = np.clip(noisy, 0, 255).astype(np.uint8)

# ------------------------------------------------------------
# Step 3: Noise Reduction
# ------------------------------------------------------------

# Gaussian Filter
gaussian = cv2.GaussianBlur(noisy, (5,5), 0)

# Median Filter
median = cv2.medianBlur(noisy, 5)

# ------------------------------------------------------------
# Step 4: Display Images
# ------------------------------------------------------------

plt.figure(figsize=(12,8))

plt.subplot(2,2,1)
plt.imshow(image, cmap='gray')
plt.title("Original Image")
plt.axis("off")

plt.subplot(2,2,2)
plt.imshow(noisy, cmap='gray')
plt.title("Noisy Image")
plt.axis("off")

plt.subplot(2,2,3)
plt.imshow(gaussian, cmap='gray')
plt.title("Gaussian Filter")
plt.axis("off")

plt.subplot(2,2,4)
plt.imshow(median, cmap='gray')
plt.title("Median Filter")
plt.axis("off")

plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# Step 5: Save Images
# ------------------------------------------------------------

cv2.imwrite("original_image.jpg", image)
cv2.imwrite("noisy_image.jpg", noisy)
cv2.imwrite("gaussian_filtered.jpg", gaussian)
cv2.imwrite("median_filtered.jpg", median)

print("Experiment Completed Successfully!")
print("Images Saved:")
print("1. original_image.jpg")
print("2. noisy_image.jpg")
print("3. gaussian_filtered.jpg")
print("4. median_filtered.jpg")